library(readr)
library(janitor)
library(dplyr)
library(stringr)
library(readODS)
library(sidrar)
library(tidyr)


# Importar dados ----------------------------------------------------------

base_rms <- read_ods("F:/Projetos/Mobilidados/datasus_verificacao/dados/Composicao_RMs_RIDEs_AglomUrbanas_2020_06_30.ods") %>% 
  mutate(COD_MUN = as.character(substr(COD_MUN, 1, 6)) ) %>% select(NOME, COD_MUN)


#Tem dois municípios que estão em mais de uma RM. Retirar a classificação mais antiga.

base_rms <- subset(base_rms, !c(c(base_rms$COD_MUN == 270900 & base_rms$NOME != "Região Metropolitana do Agreste")))
base_rms <- subset(base_rms, !c(c(base_rms$COD_MUN == 270550 & base_rms$NOME != "Região Metropolitana de Maceió")))


# Baixando os dados de população dos municípios ---------------------------

anos <- as.character(2001:2021) # Modificar o ano quando atualizar

tabela_pop <- NULL

for(i in anos){
  tmp <- get_sidra(x = 6579, # código da tabela
                   variable = 9324, # Código da variável
                   geo = "City", # Site
                   period = i)
  tabela_pop <- rbind(tabela_pop, tmp)
}

# Os anos dos censos precisam ser baixados separadamente

tabela_pop_2000 <- get_sidra(x = 200, # código da tabela
                             variable = 93,# Código da variável
                             geo = "City", # Site
                             period = "2000",
                             classific = c("c2"),
                             category = list(0))

tabela_pop_2010 <- get_sidra(x = 1378, # código da tabela
          variable = 93,# Código da variável
          geo = "City", # Site
          period = "2010",
          classific = c("c1"),
          category = list(0))

tabela_pop_2007 <- get_sidra(x = 793, # código da tabela
           # Código da variável
          geo = "City", # Site
          period = "2007")

# Juntar todos os anos

tabela_pop_f <- rbind(tabela_pop, tabela_pop_2010[,1:11],tabela_pop_2007,tabela_pop_2000[,1:11])


# Limpeza de dados --------------------------------------------------------

# Dados serão limpos e colocados no formato para subir para a mobilidados

tabela_pop2 <- tabela_pop_f %>% clean_names() %>% mutate(uf = str_sub(municipio, -2, -1), # cria a coluna com nome de uf
                                                       municipio = str_sub(municipio, 1, -6), # coluna somente com nome do município
                                                       COD_MUN = str_sub(municipio_codigo,1,-2)) # cria coluna com o cósigo do município caracter a menos

ordem <- c(2000:2021)

tabela_pop3 <- tabela_pop2 %>% mutate(ano = factor(ano, levels = ordem)) %>% arrange(ano)

tabela_pop_rm <- tabela_pop3 %>% left_join(base_rms, c("COD_MUN" = "COD_MUN"))


capitais <- c(1100205,1200401,1302603,1400100,1501402,1600303,
              1721000,2111300,2211001,2304400,2408102,2507507,
              2611606,2704302,2800308,2927408,3106200,3205309,
              3304557,3550308,4106902,4205407,4314902,5002704,
              5103403,5208707,5300108)


# Formatação e organização das tabelas

tabela_pop_rm <- tabela_pop_rm %>% mutate(capitais = case_when(
  tabela_pop_rm$municipio_codigo %in% capitais ~ "Sim",
  tabela_pop_rm$municipio_codigo %in% capitais == FALSE ~"Não"))

tabela_pop_rm$cod_uf <- str_sub(tabela_pop_rm$municipio_codigo,1,2)
tabela_pop_rm$COD_MUN <- str_sub(tabela_pop_rm$municipio_codigo,1,-2)

tabela_pop_rm2 <- tabela_pop_rm %>% 
   select(cod_uf,uf,municipio_codigo,COD_MUN, municipio,  capitais, NOME,  ano, valor) %>% 
  pivot_wider(names_from = ano, values_from = valor, values_fill = 0) 

tabela_pop_rm3 <- tabela_pop_rm %>% 
  select(cod_uf,uf,municipio_codigo,COD_MUN, municipio, capitais, NOME, ano, valor)

tabela_pop_capitais <- tabela_pop_rm %>% 
  filter(capitais == "Sim")

pop_capitais_final <- tabela_pop_capitais[match(capitais, tabela_pop_capitais$municipio_codigo),]

tabela_pop_rms_final <- tabela_pop_rm3[,c(7,8,9)] %>% 
  group_by(NOME, ano) %>% 
  summarise(valor = sum(valor, na.rm = TRUE)) %>%
  pivot_wider(names_from = ano, values_from = valor)


#Seleção de Regiões Metropolitanas monitradas na MobiliDADOS

rms_sel <- c("Região Metropolitana de Belém","Região Metropolitana de Belo Horizonte",
             "Região Metropolitana de Curitiba","Região Integrada de Desenvolvimento do Distrito Federal e Entorno",
             "Região Metropolitana de Fortaleza","Região Metropolitana do Recife","Região Metropolitana do Rio de Janeiro",
             "Região Metropolitana de Salvador","Região Metropolitana de São Paulo")


# Filtrar pelas RMs selecionas

tabela_pop_rms_final2 <- tabela_pop_rms_final %>% filter(NOME %in% rms_sel) 

# Coloca as linhas em ordem

tabela_pop_rms_final2 <- tabela_pop_rms_final[match(rms_sel, tabela_pop_rms_final$NOME),]


# Salva os arquivos em csv e rds

write.csv2(tabela_pop_rm2, "F:/Projetos/mobilidados/populacao/output/tabela_pop.csv", row.names = FALSE)
write.csv2(tabela_pop_rm3, "F:/Projetos/mobilidados/populacao/output/tabela_pop_base.csv", row.names = FALSE)
write.csv2(tabela_pop_capitais, "F:/Projetos/mobilidados/populacao/output/tabela_pop_capitais.csv", row.names = FALSE)
write.csv2(tabela_pop_rms_final2, "F:/Projetos/mobilidados/populacao/output/tabela_pop_rms_final2.csv", row.names = FALSE)
write.csv2(tabela_pop_rms_final, "F:/Projetos/mobilidados/populacao/output/tabela_pop_rms_final.csv", row.names = FALSE)

write_rds(tabela_pop_rm2, "F:/Projetos/mobilidados/populacao/output/tabela_pop.rds")
write_rds(tabela_pop_rm3, "F:/Projetos/mobilidados/populacao/output/tabela_pop_base.rds")
write_rds(tabela_pop_capitais, "F:/Projetos/mobilidados/populacao/output/tabela_pop_capitais.rds")
write_rds(tabela_pop_rms_final2, "F:/Projetos/mobilidados/populacao/output/tabela_pop_rms_final2.rds")
write_rds(tabela_pop_rms_final, "F:/Projetos/mobilidados/populacao/output/tabela_pop_rms_final.rds")
