rem Arquivo executável para criar as pastas já de uma maneira organizada

call mkdir ara
call mkdir bel
call mkdir bho
call mkdir boa
call mkdir cam
call mkdir cui
call mkdir cur
call mkdir dis
call mkdir flo
call mkdir for
call mkdir goi
call mkdir joa
call mkdir mac
call mkdir man
call mkdir mco
call mkdir nat
call mkdir pal
call mkdir poa
call mkdir por
call mkdir rbr
call mkdir rec
call mkdir ride
call mkdir rio
call mkdir rmb
call mkdir rmbh
call mkdir rmc
call mkdir rmf
call mkdir rmr
call mkdir rmrj
call mkdir rms
call mkdir rmsp
call mkdir sls
call mkdir spo
call mkdir ssa
call mkdir ter
call mkdir vit
