#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
###### Download de shape file de municipios e setores censitarios dos  municipios incluidos no projeto

# carregar bibliotecas
source('./0_setup.R')

## 1. lista de municipios no projeto
list_muni_codes <- munis_df$code_muni

# criar pasta do municipios
lapply( paste0('./dados/', unique(munis_df$rm)), dir.create)
lapply( paste0('./dados/', unique(munis_df$rm), '/municipios'), dir.create)
lapply( paste0('./dados/', unique(munis_df$rm), '/setores'), dir.create)


# 2. Funcao para download de shape file dos municipios e setores censitarios
download_muni_setores <- function(i){
  
  #sigla <- ifelse(i %in% as.numeric(munis_df$code_muni), 
  #                as.character(munis_df$name_muni), NA)
  
  sigla <- munis_df %>% filter(code_muni == i) %>% 
    mutate(name_muni = as.character(name_muni)) %>%
    .$name_muni
  
  # Download de arquivos
  muni_sf <- geobr::read_municipality(code_muni=i, year=2010)
  ct_sf <- geobr::read_census_tract(code_tract =i, year=2010)
  
  
  # salvar municipios
  readr::write_rds(muni_sf, paste0('./dados/', subset(munis_df, code_muni==i)$rm, '/municipios/municipio_', sigla,'.rds'))
  
  #readr::write_rds(muni_sf, paste0("../data-raw/municipios/",sigla,"/municipio_", sigla,".rds"))
  
  # salvar setores censitarios
  readr::write_rds(ct_sf, paste0('./dados/', subset(munis_df, code_muni==i)$rm, '/setores/setores_', sigla,'.rds'))
                   
  #readr::write_rds(ct_sf, paste0("../data-raw/setores_censitarios/", sigla,"/setores_", sigla,".rds"))
}

# 3. Aplica funcao
lapply(X=list_muni_codes, FUN=download_muni_setores)
