# definir diretorio
setwd('E:/R/')

# abrir pacotes necessarios
library(datasus)
library(stringi)
library(sf)
library(dplyr)
library(data.table)
library(openxlsx)
library(pbapply)
library(beepr)


# i = "outros"

# criar funcao 
taxa_mortalidade <- function(i) {
  
  message(paste0("abrindo arquivos para calcular mortalidade de ", i , "..."))
  
  # abrir tabelas de mortes
  mortes <- read.xlsx(paste0("./dados/datasus/2018/", i, "_mortes_2018.xlsx"))
  mortes[is.na(mortes)]<- 0
  
  # abrir tabela de população
  pop <- read.xlsx("./dados/IBGE/estimativas_populacao/serie_historica/pop_2000_2019.xlsx") %>%
    filter(CD_MUN != 1)
  pop[is.na(pop)]<- 0
  
  
  beep()
  
  
  message("unindo mortes e populacao...")
  # unir 
  mortes_pop <- left_join(pop, mortes, by = c("CD_MUN6"= "code_muni6")) %>% mutate(regiao_metro = NULL)
  
  message("calculando taxa de mortalidade...")
  # calcular taxa de mortalidade
  setDT(mortes_pop)
  mortalidade <- setDT(mortes_pop) [, .(tx_mort_2000 = round((`2000`/Pop_2000)*100000, digits = 1),
                                        tx_mort_2001 = round((`2001`/Pop_2001)*100000, digits = 1),
                                        tx_mort_2002 = round((`2002`/Pop_2002)*100000, digits = 1),
                                        tx_mort_2003 = round((`2003`/Pop_2003)*100000, digits = 1),
                                        tx_mort_2004 = round((`2004`/Pop_2004)*100000, digits = 1),
                                        tx_mort_2005 = round((`2005`/Pop_2005)*100000, digits = 1),
                                        tx_mort_2006 = round((`2006`/Pop_2006)*100000, digits = 1),
                                        tx_mort_2007 = round((`2007`/Pop_2007)*100000, digits = 1),
                                        tx_mort_2008 = round((`2008`/Pop_2008)*100000, digits = 1),
                                        tx_mort_2009 = round((`2009`/Pop_2009)*100000, digits = 1),
                                        tx_mort_2010 = round((`2010`/Pop_2010)*100000, digits = 1),
                                        tx_mort_2011 = round((`2011`/Pop_2011)*100000, digits = 1),
                                        tx_mort_2012 = round((`2012`/Pop_2012)*100000, digits = 1),
                                        tx_mort_2013 = round((`2013`/Pop_2013)*100000, digits = 1),
                                        tx_mort_2014 = round((`2014`/Pop_2014)*100000, digits = 1),
                                        tx_mort_2015 = round((`2015`/Pop_2015)*100000, digits = 1),
                                        tx_mort_2016 = round((`2016`/Pop_2016)*100000, digits = 1),
                                        tx_mort_2017 = round((`2017`/Pop_2017)*100000, digits = 1),
                                        tx_mort_2018 = round((`2018`/Pop_2018)*100000, digits = 1)), 
                                    by = CD_MUN6]
  
  # agregar variaveis para arquivo final
  message("organizando arquivo final...")
  fim <- left_join(pop %>% select(CD_MUN, CD_MUN6, MUN, CAPITAL, RM), mortalidade, by = "CD_MUN6")
  # final <- left_join(fim, mortes %>% select(code_muni6, tipo), by = c("CD_MUN6"="code_muni6"))
  
  names(fim)
  
  # reordenar colunas
  fim <- fim %>% mutate(tipo = i)
  
  final <- fim[,c(1, 2, 3, 4, 24, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,23)]
  final[is.na(final)]<- 0
  
  # salvar arquivo final
  message("salvando arquivo final...")
  write.xlsx(final, paste0("./resultados/datasus/2018/muni_", i, "_taxa_mortalidade.xlsx"))
  
  return(final)
  beep()
  
  
}

# aplicar funcao para um caso
resultado <- taxa_mortalidade("pedestres")


# aplicar funcao para todos
pblapply(c("total", "pedestres", "ciclistas", 
           "motociclistas", "ocupantes_auto", "outros"), 
         taxa_mortalidade)
