# definir diretorio
setwd('E:/R/')

# abrir pacotes necessarios
library(datasus)
library(stringi)
library(sf)
library(dplyr)
library(data.table)
library(openxlsx)
library(pbapply)
library(beepr)

# criar funcao 
taxa_mortalidade <- function(i) {
 
  message(paste0("abrindo arquivos para calcular mortalidade de ", i , "..."))
  
  # abrir tabelas de mortes
  mortes <- read.xlsx(paste0("./dados/datasus/2018/", i, "_mortes_2018.xlsx"))
  
  # abrir tabela de população
  pop <- read.xlsx("./dados/IBGE/estimativas_populacao/serie_historica/pop_2000_2019.xlsx")
  
  beep()
  
  
  message("unindo mortes e populacao...")
  # unir 
  mortes_pop <- left_join(pop, mortes, by = c("CD_MUN6"= "code_muni6"))
  
  
  message("calculando taxa de mortalidade...")
  # calcular taxa de mortalidade
  setDT(mortes_pop)
  mortalidade <- setDT(mortes_pop) [, .(tx_mort_2000 = round((`2000`/Pop_2000)*100000, digits = 1),
                                        tx_mort_2001 = round((`2001`/Pop_2001)*100000, digits = 1),
                                        tx_mort_2002 = round((`2002`/Pop_2002)*100000, digits = 1),
                                        tx_mort_2003 = round((`2003`/Pop_2003)*100000, digits = 1),
                                        tx_mort_2004 = round((`2004`/Pop_2004)*100000, digits = 1),
                                        tx_mort_2005 = round((`2005`/Pop_2005)*100000, digits = 1),
                                        tx_mort_2006 = round((`2006`/Pop_2006)*100000, digits = 1),
                                        tx_mort_2007 = round((`2007`/Pop_2007)*100000, digits = 1),
                                        tx_mort_2008 = round((`2008`/Pop_2008)*100000, digits = 1),
                                        tx_mort_2009 = round((`2009`/Pop_2009)*100000, digits = 1),
                                        tx_mort_2010 = round((`2010`/Pop_2010)*100000, digits = 1),
                                        tx_mort_2011 = round((`2011`/Pop_2011)*100000, digits = 1),
                                        tx_mort_2012 = round((`2012`/Pop_2012)*100000, digits = 1),
                                        tx_mort_2013 = round((`2013`/Pop_2013)*100000, digits = 1),
                                        tx_mort_2014 = round((`2014`/Pop_2014)*100000, digits = 1),
                                        tx_mort_2015 = round((`2015`/Pop_2015)*100000, digits = 1),
                                        tx_mort_2016 = round((`2016`/Pop_2016)*100000, digits = 1),
                                        tx_mort_2017 = round((`2017`/Pop_2017)*100000, digits = 1),
                                        tx_mort_2018 = round((`2018`/Pop_2018)*100000, digits = 1)), 
                                    by = CD_MUN6]
  
  # agregar variaveis para arquivo final
  message("organizando arquivo final...")
  fim <- left_join(pop %>% select(CD_UF, UF, CD_MUN6, MUNICIPIO), mortalidade, by = "CD_MUN6")
  final <- left_join(fim, mortes %>% select(code_muni6, regiao_metro, tipo), by = c("CD_MUN6"="code_muni6"))%>%
    rename(RM = regiao_metro) 
  
  # agregar variavel de capitais
  munis_df <- data.frame(code_muni = c(2927408,  3550308,  3304557,  2611606,  2304400,  
                                       5300108,  4106902,  3106200,  1501402,  1100205,  
                                       1200401,  1302603,  1400100,  1600303,  1721000,  
                                       2111300,  2211001,  2408102,  2507507,  2704302,  
                                       2800308,  3205309,  4205407,  4314902,  5002704, 
                                       5103403,  5208707), 
                         name_muni=c('salvador',  'sao paulo', 'rio de janeiro',  'recife', 
                                     'fortaleza',  'distrito federal',  'curitiba',  
                                     'belo horizonte',  'belem',  'porto velho',  'rio branco',  
                                     'manaus',  'boa vista',  'macapa',  'palmas',  'sao luis', 
                                     'teresina',  'natal',  'joao pessoa',  'maceio',  'aracaju',  
                                     'vitoria',  'florianopolis',  'porto alegre',  'campo grande',  
                                     'cuiaba',  'goiania'), 
                         abrev_state=c('BA',  'SP',  'RJ',  'PE',  'CE',  'DF',  'PR',  'MG',  'PA',  'RO', 
                                       'AC',  'AM',  'RR',  'AP',  'TO',  'MA',  'PI',  'RN',  'PB',  'AL', 
                                       'SE',  'ES',  'SC',  'RS',  'MS',  'MT',  'GO'),  
                         espg = c(31984,  31983,  31983,  31985,  31984,  31983,  31982,  31983,  31982,  
                                  31980,  31979,  31980,  31980,  31982,  31982,  31983,  31983, 
                                  31985,  31985,  31985,  31984,  31984,  31982,  31982,  31981, 
                                  31981,  31982), 
                         sigla_muni = c("ssa",  "spo",  "rio",  "rec",  "for",  "dis",  "cur",  
                                        "bho",  "bel",  "por",  "rbr",  "man",  "boa",  "mac",  
                                        "pal",  "sls",  "ter",  "nat",  "joa",  "mco",  "ara",  
                                        "vit",  "flo",  "poa",  "cam",  "cui",  "goi"))
  
  
  final$CAPITAL <- ifelse(final$CD_MUN6 %in% munis_df$CD_MUN6, "Sim", "Não") 

  # reordenar colunas
  final <- final[,c(1, 2, 3, 4, 24, 26, 25, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,23)]

  # salvar arquivo final
  message("salvando arquivo final...")
  write.xlsx(final, paste0("./resultados/datasus/2018/", i, "_taxa_mortalidade.xlsx"))
  
  return(final)
  beep()
  
    
}

# aplicar funcao para um caso
resultado <- taxa_mortalidade("outros")


# aplicar funcao para todos
pblapply(c("total", "pedestres", "ciclistas", 
           "motociclistas", "ocupantes_auto", "outros"), 
         taxa_mortalidade)
