# carregar pacotes
library(sf)
library(openxlsx)
library(tidyverse)
library(mapview)
library(janitor)

# definir diretorio
setwd('E:/R/')

# criar tabela de referencia para capitais
munis_df <- data.frame(code_muni = c(2927408, 3550308, 3304557, 2611606, 2304400, 5300108, 4106902,
                                     3106200, 1501402, 1100205, 1200401, 1302603, 1400100, 1600303, 
                                     1721000, 2111300, 2211001, 2408102, 2507507, 2704302, 2800308,
                                     3205309, 4205407, 4314902, 5002704, 5103403, 5208707),
                       name_muni=c('salvador', 'sao paulo','rio de janeiro', 'recife',
                                   'fortaleza', 'brasilia', 'curitiba', 
                                   'belo horizonte', 'belem', 'porto velho', 'rio branco', 
                                   'manaus', 'boa vista', 'macapa', 'palmas', 'sao luis',
                                   'teresina', 'natal', 'joao pessoa', 'maceio', 'aracaju', 
                                   'vitoria', 'florianopolis', 'porto alegre', 'campo grande', 
                                   'cuiaba', 'goiania'),
                       abrev_state=c('BA', 'SP', 'RJ', 'PE', 'CE', 'DF', 'PR', 'MG', 'PA', 'RO',
                                     'AC', 'AM', 'RR', 'AP', 'TO', 'MA', 'PI', 'RN', 'PB', 'AL',
                                     'SE', 'ES', 'SC', 'RS', 'MS', 'MT', 'GO'), 
                       espg = c(31984, 31983, 31983, 31985, 31984, 31983, 31982, 31983, 31982, 
                                31980, 31979, 31980, 31980, 31982, 31982, 31983, 31983,
                                31985, 31985, 31985, 31984, 31984, 31982, 31982, 31981,
                                31981, 31982),
                       sigla_muni = c("ssa", "spo", "rio", "rec", "for", "dis", "cur", 
                                      "bho", "bel", "por", "rbr", "man", "boa", "mac", 
                                      "pal", "sls", "ter", "nat", "joa", "mco", "ara", 
                                      "vit", "flo", "poa", "cam", "cui", "goi"))

# teste
# i  = 'dis'
# j = '2019'
# rm(j)


# criar funcao para calcular o indicador

perc_tma_prox_infra_ciclo <- function (i, j){
  
  #Abrir infraestrutura cicloviaria
  buf_infra_ciclo <- read_rds(paste0('./codigos/tt_isochrones-master/output/pnb/', k, '/', subset(munis_df, sigla_muni==i)$name_muni, '_network_buffer.rds'))   #buffer com distancia real
  buf_infra_ciclo <- st_transform(buf_infra_ciclo,  subset(munis_df, sigla_muni==i)$espg)
  buf_infra_ciclo <- buf_infra_ciclo %>% st_set_precision(1000000) %>% sf::st_make_valid() #corrigir shapes que podem possuir algum defeito de feicao
  
  message('abriu buffer')
  
  #abrir estacoes
  stations <- st_read(paste0('./dados/infra_transporte/tma/', k, '/v10072020/', 'all_stations.shp')) %>% #inserir o nome do arquivo no qual salvou as estacoes para abri-lo
    mutate(Ano = as.numeric(as.character(Year)),
           Cidade = rm_accent(tolower(City))) %>% #transforma a coluna de ano em valor numerico
    filter(Ano <= k, Status =='Operational', RT == 'Yes', Cidade %in% subset(munis_df, sigla_muni==i)$name_muni)
  
  unique(stations)
  
  stations <- st_transform(stations, subset(munis_df, sigla_muni==i)$espg)
  
  message('abriu e filtrou estacoes')
  
  muni <- st_read('E:/R/dados/IBGE/br_municipios/munis_br.shp') %>%
    filter(code_mn %in% subset(munis_df, sigla_muni==i)$code_muni) 
  
  muni <- st_transform(muni, subset(munis_df, sigla_muni==i)$espg)
  
  message('abriu e filtrou municipio')
  
  # verificar projecao
  # st_crs(muni)
  # st_crs(stations)
  # st_crs(buf_infra_ciclo)
  
  stations_cid <- st_intersection(stations, muni)
  
  # mapview(stations_cid) + mapview(buf_infra_ciclo)
  
  # intersectar para encontrar valores dentro e fora do buffer
  results <- st_intersects(stations_cid, buf_infra_ciclo, sparse = F)
  
  fim <- as.data.frame(table(results)) %>% adorn_totals("row") # calcular total
  
  # renomear colunas
  final <- as.data.frame(t(fim)) 
  names(final) <- as.matrix(final[1, ])
  final <- final[-1, ]
  
  # calcular percentual
  resultados <- final %>% 
    dplyr::rename(out = `FALSE`, `in` = `TRUE`, total = Total) %>%
    dplyr::mutate(out = as.numeric(out), `in` = as.numeric(`in`), total = as.numeric(total), 
                  perc_out = round(100*(out/total),0),
                  perc_in = round(100*(`in`/total),0), 
                  cidade = subset(munis_df, sigla_muni==i)$name_muni)
  
  
  # library(Hmisc)
  # capitalize(name)
  # i = "rio"
  # capitalize(subset(munis_df, sigla_muni==i)$name_muni)
  
  return(resultados)
  
  
}

# aplicar funcao por municipio
bel <- perc_tma_prox_infra_ciclo('bel', 2019)  #funcao nao funcionou porque todas as estacoes estao proximas da infraestrutura cicloviaria
bho <- perc_tma_prox_infra_ciclo('bho', 2019)  #ok
cur <- perc_tma_prox_infra_ciclo('cur', 2019)  #ok
fort <- perc_tma_prox_infra_ciclo('for', 2019) #ok
dis <- perc_tma_prox_infra_ciclo('dis', 2019)  #ok
rec <- perc_tma_prox_infra_ciclo('rec', 2019)  #ok
rio <- perc_tma_prox_infra_ciclo('rio', 2019)  #ok
ssa <- perc_tma_prox_infra_ciclo('ssa', 2019)  #ok
spo <- perc_tma_prox_infra_ciclo('spo', 2019)  #ok


# criar tabela final 
resultado_final <- rbind(bho,cur,fort,dis,rec,rio,ssa,spo) %>%
  rbind(c(0,22,22, 0, 100, "belem"))

# ordenar resultados
resultado_final[order(resultado_final$cidade),]
